DROP TABLE IF EXISTS item;
CREATE TABLE item (
    id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    bid INT UNSIGNED NOT NULL,
    name VARCHAR(512) NOT NULL,
    price INT UNSIGNED NOT NULL DEFAULT 0,
    pic MediumBlob,
    `desc` TEXT,
    status TINYINT NOT NULL DEFAULT 0,
    update_at DATETIME DEFAULT NOW(),
    create_at DATETIME DEFAULT NOW()
) DEFAULT CHARSET=utf8mb4;

ALTER TABLE `item` ADD INDEX(bid, status);
