DROP TABLE IF EXISTS order_log;
CREATE TABLE order_log (
    id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    buid INT UNSIGNED,
    cuid INT UNSIGNED,
    oid INT UNSIGNED NOT NULL,
    op VARCHAR(32) NOT NULL,
    new TEXT,
    create_at DATETIME DEFAULT NOW()
) DEFAULT CHARSET=utf8mb4;

ALTER TABLE order_log ADD INDEX(oid);
